name: "Deploy"

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

env:
  AWS_REGION_DEFAULT: us-east-1

jobs:
  rds:
    name: "Build & Check - AWS RDS"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION_DEFAULT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform -chdir=rds init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=rds validate -no-color

      - name: Terraform Apply
        env:
          TF_VAR_accountId: ${{ secrets.AWS_ACCOUNT_ID }}
        run: terraform -chdir=rds apply -auto-approve -input=false

  elasticache:
    name: "Build & Check - AWS Elasticache"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION_DEFAULT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform -chdir=elasticache init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=elasticache validate -no-color

      - name: Terraform Apply
        env:
          TF_VAR_accountId: ${{ secrets.AWS_ACCOUNT_ID }}
        run: terraform -chdir=elasticache apply -auto-approve -input=false
